config/routes.rb
Rails.application.routes.draw do

  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :subjects do
    member do
      get :delete
    end

    # for collection actions:
    # collection do
    #   get :export
    # end

  end
  resources :pages do
    member do
      get :delete
    end
  end

  resources :users do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :subject
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.order("position ASC")
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to(pages_path)
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      redirect_to(page_path)
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to(pages_path)
  end
end


private

def page_params
  params.require(:page).permit(:name, :permalink, :visible, :position, :content, :subject_id)
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.order('position ASC')
  end

  def show
    @pages = Page.where(:subject_id => params[:id], :visible => true)
  end

  def new
    @subject = Subject.new
  end

  def create
    # Instantiate a new object using form parameters
    @subject = Subject.new(subject_params)
    # Save the object
    if @subject.save
    # If save succeeds, redirect to the index action
      redirect_to(subjects_path)
    else
    # If save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    redirect_to(subjects_path)
  end

  private

  def subject_params
    # require presence of an object to save, allow mass assignment of form fields
    params.require(:subject).permit(:name, :visible, :position)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id = "error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved.</h2>
    <p> There were problems with the following fields:</p>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_admin_toolbar.html.erb
<nav role = 'navigation' aria-label = 'admin toolbar' class = 'admin-toolbar'>
  <div class = 'toolbar-header'>Admin tools</div>
  <%= link_to('Subjects', subjects_path, class: 'menu-button') %>
  <%= link_to('Pages', pages_path, class: 'menu-button') %>
  <%= link_to('Users', users_path, class: 'menu-button') %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Oswald|Pacifico|Roboto&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <h1>MySite</h1>
  </header>

  <!-- Subject navigation bar -->
  <nav role = 'navigation' aria-label = 'subjects menu' class = 'subject-menu'>
    <div class = 'toolbar-header'>Subjects:</div>
    <% Subject.order('position ASC').where(:visible => true).each do |subject|%>
      <%= link_to(subject.name, subject_path(subject.id), class: 'menu-button') %>
    <% end %>
    <%= link_to('log in', access_login_path, class: 'menu-button', id: 'login-button') %>
  </nav>
  <!-- Admin navigation bar -->
  <%= render(:partial => 'layouts/admin_toolbar') %>
  <!-- Yield -->
  <div class = "content"><%= yield %></div>
  <footer>
    Powered by Simple CMS
  </footer>
  </body>
</html>

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary = "Page form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
    <th>Position</th>
   <td><%= f.text_field(:position) %></td>
  </tr>
   <th>Visible</th>
   <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Subject</th>
    <td><%= f.collection_select(:subject_id, Subject.all, :id, :name) %></td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= f.text_area(:content) %></td>
  </tr>
</table>

app/views/pages/delete.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class = "pages delete">
  <h2>Delete Subject</h2>

  <%= form_for(@page, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this page?</p>
    <p><%= @page.name %></p>

    <div class = "form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class = "page edit">
  <h2>Edit Page</h2>

  <%= form_for(@page) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class = "form-buttons">
      <%= f.submit("Update Page") %>
    </div>

  <% end %>
</div>

app/views/pages/index.html.erb
<div class = "pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page", new_page_path, :class => 'action new') %>

  <table class = "listing" summary = "Pages list">
    <tr class = "header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Subject</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.position %></td>
        <td><%= page.name %></td>
        <td class = "center"><%= page.visible ? 'Yes' : "No" %></td>
        <td class = "center"><%= page.subject.name %></td>
        <td class = "actions">
          <%= link_to("Show", page_path(page), :class => 'action-show') %>
          <%= link_to("Edit", edit_page_path(page), :class => 'action-edit') %>
          <%= link_to("Delete", delete_page_path(page), :class => 'action-delete') %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class = "pages new">
  <h2>Create Page</h2>

  <%= form_for(@page, :url => pages_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class = "form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>
</div>

app/views/pages/show.html.erb
<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>
<br/>
<%= link_to("Edit", edit_page_path) %>

<div class = "subjects show">
  <h2><%= @page.name %></h2>
  <h3><%= @page.subject.name %></h3>
  <h4>Written <%= @page.created_at.strftime("%B %d, %Y %l:%M %p") %></h4>

  <% if @page.created_at != @page.updated_at %>
    <h4>Updated <%= @page.updated_at %></h4>
  <% end %>

  <p><%= @page.content %></p>
</div>

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary = "Subject form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <th>Position</th>
  <td><%= f.text_field(:position) %></td>
  </tr>
  <th>Visible</th>
  <td><%= f.text_field(:visible) %></td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class = "subjects delete">
  <h2>Delete Subject</h2>

  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>
    <p><%= @subject.name %></p>

    <div class = "form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class = "subjects edit">
  <h2>Edit Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class = "form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<div class = "subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class = "listing" summary = "Subjects list">
    <tr class = "header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class = "center"><%= subject.visible ? 'Yes' : "No" %></td>
      <td class = "center"><%= subject.pages.size %></td>
      <td class = "actions">
        <%= link_to("Show", subject_path(subject), :class => 'action-show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action-edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action-delete') %>
      </td>
    </tr>
      <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class = "subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class = "form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

    <% end %>
</div>

app/views/subjects/show.html.erb
<% @pages.each do |page| %>
  <article class = 'page'>
    <h2><%= link_to(page.name, page_path(page[:id])) %></h2>
    <p><%= page.content %></p>
  </article>
<% end %>